/* eslint-disable key-spacing,key-spacing,no-trailing-spaces,no-undef */
/**
 * Created by viktor on 7/6/17.
 */

// ========================================================
// Import Entities
// ========================================================

import { GOAL_ENTITIES } from '../Utility/Mapper/Goal'
import { CHILD_ENTITIES } from '../Utility/Mapper/Child'
import { AUTH_ENTITIES } from '../Utility/Mapper/Auth'
import { USER_ENTITIES } from '../Utility/Mapper/User'
import { COMMON_ENTITIES } from '../Utility/Mapper/Common'
import { SETTINGS_ENTITIES } from '../Utility/Mapper/Settings'

// ========================================================
// Export parameters
// ========================================================

export default {

  // ------------ goal parameters ------------

  ADD_CUSTOM_GOAL : [GOAL_ENTITIES.USER_ID, GOAL_ENTITIES.CID, GOAL_ENTITIES.NAME, CHILD_ENTITIES.FIRST_NAME, COMMON_ENTITIES.NAVIGATOR, GOAL_ENTITIES.RISK_SELECTED],
  ADD_CUSTOM_GOAL_SUCCESS : [GOAL_ENTITIES.CID, GOAL_ENTITIES.GID, GOAL_ENTITIES.NAME, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE, USER_ENTITIES.USER_ID, GOAL_ENTITIES.RISK_SELECTED],
  ADD_CUSTOM_GOAL_FAILURE : ['error'],

  GOAL_TYPE_SELECTED: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],
  GOAL_DURATION_SELECTED: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE],
  GOAL_DURATION_SELECTION_NEEDED: [GOAL_ENTITIES.GOAL_DURATION_TYPE, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR_TITLE, COMMON_ENTITIES.NAVIGATOR],
  SELECT_RISK: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE],
  COST_EXPECTED_SELECTED: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR_TITLE, COMMON_ENTITIES.NAVIGATOR],
  ADD_RISK: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE],
  GOAL_AMOUNT_SELECTED: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE],
  SHOW_INVEST: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.IS_STALE],
  HIDE_INVEST: [COMMON_ENTITIES.NAVIGATOR],

  UPDATE_COMPLETE_GOAL: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.GOAL_AMOUNT, GOAL_ENTITIES.IS_RECURRING, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, GOAL_ENTITIES.FIRST_TRANSFER_DATE, COMMON_ENTITIES.NAVIGATOR],
  UPDATE_PARTIAL_GOAL: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.GOAL_AMOUNT, GOAL_ENTITIES.PORTFOLIO_RISK, COMMON_ENTITIES.NAVIGATOR],
  UPDATE_GOAL_SUCCESS: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.GOAL_DATA, COMMON_ENTITIES.NAVIGATOR],
  UPDATE_GOAL_FAILURE: ['error'],

  NAVIGATE_TO_EDIT_GOAL: [GOAL_ENTITIES.CID, GOAL_ENTITIES.GID],
  EDIT_GOAL: [GOAL_ENTITIES.CID, GOAL_ENTITIES.GID, GOAL_ENTITIES.NAME, GOAL_ENTITIES.GOAL_AMOUNT, GOAL_ENTITIES.INITIAL_DEPOSIT, GOAL_ENTITIES.MM, GOAL_ENTITIES.DD, GOAL_ENTITIES.YYYY],

  INVEST_ON_GOAL: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],
  NAVIGATE_TO_HOMEPAGE: [COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_TRANSFER_SCREEN: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],
  TRANSFER: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, GOAL_ENTITIES.ONE_OFF_INVESTMENT, COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.CHILD_IDs],
  TRANSFER_SUCCESS: [COMMON_ENTITIES.NAVIGATOR],
  TRANSFER_FAILURE: [COMMON_ENTITIES.NAVIGATOR],

  FETCH_GOAL_DETAIL: [USER_ENTITIES.USER_ID, GOAL_ENTITIES.GID],
  FETCH_GOAL_DETAIL_SUCCESS: [GOAL_ENTITIES.GOAL_DATA],
  FETCH_GOAL_DETAIL_FAILURE: ['error'],

  FETCH_GOAL_CHART_DATA: [GOAL_ENTITIES.GID],
  FETCH_GOAL_CHART_DATA_SUCCESS: [GOAL_ENTITIES.GID, GOAL_ENTITIES.CHART_DATA],
  FETCH_GOAL_CHART_DATA_FAILURE: ['error'],

  CONFIRM_BANK_CONNECTION: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],
  SKIP_BANK_CONNECTION: [COMMON_ENTITIES.NAVIGATOR],
  POP_SCREEN: [COMMON_ENTITIES.NAVIGATOR],

  // ------------ child parameters ------------
  ADD_AVATAR: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.AVATAR],

  SHOW_CHILD: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],
  POP_CHILD_VIEW: [COMMON_ENTITIES.NAVIGATOR],

  ADD_CHILD: [CHILD_ENTITIES.USER_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB, CHILD_ENTITIES.SSN, USER_ENTITIES.EMAIL_ID, COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.IDENTITY_DATA],
  ADD_CHILD_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB, COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.USER_ID],
  ADD_CHILD_FAILURE: ['error'],

  FETCH_CHILDREN_DETAILS: [CHILD_ENTITIES.CHILD_IDs],
  FETCH_CHILDREN_DETAILS_SUCCESS: [],
  FETCH_CHILDREN_DETAILS_FAILURE: [],

  FETCH_CHILD_CHART_DATA: [CHILD_ENTITIES.CHILD_ID],
  FETCH_CHILD_CHART_DATA_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.CHART_DATA],
  FETCH_CHILD_CHART_DATA_FAILURE: ['error'],

  SUBMIT_CHILD_SSN: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.FIRST_NAME, COMMON_ENTITIES.NAVIGATOR],

  ADD_NEW_GOAL: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],
  ADD_NEW_CHILD: [COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_ADD_CHILD: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.RESET_STACK],
  NAVIGATE_TO_CHILD_SSN: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB, USER_ENTITIES.IDENTITY_DATA, COMMON_ENTITIES.NAVIGATOR],

  SHOW_GOAL: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.NAME, COMMON_ENTITIES.NAVIGATOR],
  HIDE_GOAL: [COMMON_ENTITIES.NAVIGATOR],

  NOTIFY_AGE_LIMITATION: [COMMON_ENTITIES.NAVIGATOR],

  // ------------ auth parameters ------------
  NAVIGATE_AUTH: [AUTH_ENTITIES.AUTH_TYPE, COMMON_ENTITIES.NAVIGATOR],

  // login user
  LOGIN:  [AUTH_ENTITIES.EMAIL, AUTH_ENTITIES.PASSWORD, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH, AUTH_ENTITIES.HELPING_SIGNUP],
  // login user success
  LOGIN_SUCCESS: [AUTH_ENTITIES.ID_TOKEN],
  // LOGIN_SUCCESS: (to be added later )
  LOGIN_FAILURE: ['error'],

  LOGOUT : [COMMON_ENTITIES.NAVIGATOR, AUTH_ENTITIES.IS_PASSCODE_LOGOUT],

  PROMPT_AUTH: [COMMON_ENTITIES.NAVIGATOR],

  PASSCODE_LOGIN: [USER_ENTITIES.EMAIL_ID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],

  SIGNUP: [AUTH_ENTITIES.EMAIL, AUTH_ENTITIES.PASSWORD, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],
  SIGNUP_SUCCESS : [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.EMAIL_ID],
  SIGNUP_FAILURE : ['error'],

  SHOW_TOUCH_ID: [COMMON_ENTITIES.NAVIGATOR],
  HIDE_TOUCH_ID: [COMMON_ENTITIES.NAVIGATOR],

  FETCH_PIN_SUCCESS: [AUTH_ENTITIES.PIN],
  FETCH_PIN_FAILURE: ['error'],

  REGISTER_PIN: [AUTH_ENTITIES.PIN, USER_ENTITIES.EMAIL_ID, AUTH_ENTITIES.PIN_ACTION_TYPE, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],
  REGISTER_PIN_SUCCESS: [AUTH_ENTITIES.PIN_ACTION_TYPE, COMMON_ENTITIES.NAVIGATOR, AUTH_ENTITIES.PIN],
  REGISTER_PIN_FAILURE: ['error'],

  // ------------ user parameters ------------
  FETCH_USER: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],
  FETCH_USER_SUCCESS: [USER_ENTITIES.USER_ID, USER_ENTITIES.USER_DATA, USER_ENTITIES.TODO_LIST],
  FETCH_USER_FAILURE: ['error'],

  FETCH_USER_DETAIL: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_IDs, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.IS_REAL_TIME],
  FETCH_USER_DETAIL_SUCCESS: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_DETAIL_DATA, COMMON_ENTITIES.NAVIGATOR],
  FETCH_USER_DETAIL_FAILURE: ['error'],

  SET_USER_ID: [USER_ENTITIES.USER_ID, USER_ENTITIES.EMAIL_ID],
  SET_USERNAME: [USER_ENTITIES.EMAIL_ID],
  NAVIGATE_USER_DETAIL_INPUT: [COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.RESIDENCY_TYPE],
  IDENTITY_CHECK_COMPLETE: [USER_ENTITIES.IDENTITY_DATA, COMMON_ENTITIES.NAVIGATOR],
  SET_PASSCODE: [COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TODO: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR],

  OPEN_ARTICLE: [COMMON_ENTITIES.NAVIGATOR],
  CLOSE_ARTICLE: [COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TC: [COMMON_ENTITIES.NAVIGATOR],
  AGREE_TC: [COMMON_ENTITIES.NAVIGATOR],
  DISAGREE_TC: [COMMON_ENTITIES.NAVIGATOR],

  // ------------ Common parameters ------------
  DISABLE_ERROR: [AUTH_ENTITIES.SHOW_ERROR],

  INITIATE_PLAID: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],
  DISMISS_PLAID: [COMMON_ENTITIES.NAVIGATOR],
  PLAID_LINKED: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, USER_ENTITIES.PLAID_ACCOUNT_ID, USER_ENTITIES.PLAID_PUBLIC_TOKEN, COMMON_ENTITIES.NAVIGATOR],
  PLAID_LINKED_SUCCESS: [COMMON_ENTITIES.NAVIGATOR],
  PLAID_LINKED_FAILURE: ['error'],

  // ------------ setting parameters ------------
  SET_ROOT_NAVIGATOR: [COMMON_ENTITIES.NAVIGATOR],
  SHOW_SETTINGS: [COMMON_ENTITIES.NAVIGATOR],
  HIDE_SETTINGS: [COMMON_ENTITIES.NAVIGATOR],
  NAVIGATE_TO_PROFILE: [COMMON_ENTITIES.NAVIGATOR],
  NAVIGATE_TO: [COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR],
  SHOW_RECURRING_WIDGET: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.RECURRING_AMOUNT, COMMON_ENTITIES.NAVIGATOR],
  SHOW_INVESTOR_QUESTIONS: [COMMON_ENTITIES.NAVIGATOR],

  CHANGE_PIN: [COMMON_ENTITIES.NAVIGATOR],

  CHANGE_PASSWORD: [COMMON_ENTITIES.NAVIGATOR],
  PROCESS_CHANGE_PASSWORD: [AUTH_ENTITIES.EMAIL, AUTH_ENTITIES.PASSWORD, AUTH_ENTITIES.NEW_PASSWORD, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],
  PROCESS_CHANGE_PASSWORD_SUCCESS: [COMMON_ENTITIES.NAVIGATOR],
  PROCESS_CHANGE_PASSWORD_FAILURE: ['error'],

  FETCH_RECURRING_DATA: [USER_ENTITIES.USER_ID],
  FETCH_RECURRING_DATA_SUCCESS: [SETTINGS_ENTITIES.RECURRING_DATA],
  FETCH_RECURRING_DATA_FAILURE: ['error'],

  SHOW_DOCUMENTS: [AUTH_ENTITIES.ID_TOKEN, COMMON_ENTITIES.NAVIGATOR],
  SHOW_DOCUMENTS_SUCCESS: [USER_ENTITIES.USER_DATA, COMMON_ENTITIES.NAVIGATOR],
  SHOW_DOCUMENTS_FAILURE: ['error'],

  SHOW_CONFIRMATIONS: [AUTH_ENTITIES.ID_TOKEN, COMMON_ENTITIES.NAVIGATOR],
  SHOW_CONFIRMATIONS_SUCCESS: [USER_ENTITIES.USER_DATA, COMMON_ENTITIES.NAVIGATOR],
  SHOW_CONFIRMATIONS_FAILURE: ['error'],

  VIEW_TRANSFERS: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR],
  VIEW_TRANSFERS_SUCCESS: [USER_ENTITIES.USER_DATA],
  VIEW_TRANSFERS_FAILURE: ['error'],
  VIEW_ACTIVITY: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR],
  SHOW_CONFIG: [COMMON_ENTITIES.NAVIGATOR],

  TRANSFER_NOW: [AUTH_ENTITIES.ID_TOKEN, COMMON_ENTITIES.NAVIGATOR],

  SHOW_WEBVIEW: [COMMON_ENTITIES.NAVIGATOR]
}

export const CHILD_PARAMETERS = {
  ADD_AVATAR: [CHILD_ENTITIES.AVATAR],

  ADD_CHILD: [CHILD_ENTITIES.USER_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB],

  ADD_CHILD_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB],
  ADD_CHILD_FAILURE: ['error']
}
